#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# This file is part of thr released under the MIT license.
# See the LICENSE file for more information.


DEFAULT_REDIS_HOST = "127.0.0.1"
DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_QUEUE = "thr:queue:default"
DEFAULT_TIMEOUT = 300
DEFAULT_BLOCKED_QUEUE_MAX_SIZE = 20
DEFAULT_HTTP_PORT = 8082
DEFAULT_MAXIMUM_LIFETIME = 300
DEFAULT_MAXIMUM_LOCAL_QUEUE_LIFETIME_MS = 1000
BRPOP_TIMEOUT = 5
REDIS_POOL_CLIENT_TIMEOUT = 60
